version: 0.1.6.1-d
#skip_non_tags: true
image: Visual Studio 2017
#configuration:
#- Debug
#- Release
environment:
  release: Release
build_script:
- cmd: msbuild "C:\projects\nekotool\NekoTool.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration="Debug"
- cmd: msbuild "C:\projects\nekotool\NekoTool.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration="Release"
before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
#build:
#  project: NekoTool.sln
#  verbosity: minimal
test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\NekoToolTest\bin\Debug\NekoToolTest.dll -noshadow" -filter:"+[NekoTool*]* -[NekoToolTest*]*" -output:".\test_coverage.xml"
- codecov -f "test_coverage.xml"
artifacts:
- path: NekoTool\bin\$(release)
  name: NekoTool-v$(appveyor_build_version)
#deploy:
#- provider: GitHub
#  tag: v$(appveyor_build_version)
#  release: v$(appveyor_build_version)
#  auth_token:
#    secure: jQxrsBnP05pmmYqIGPMTXj+zU2Stshj8H83Vhc9fMDZYBw0QMHHAP4jfxK9oEP2M
deploy: off